const languages = ['html', 'css', 'javascript', 'react', 'node', 'postgres'];
console.log(languages);
const firstElement = languages[0];
console.log('the first element of the array:', firstElement);
const thirdElement = languages[2];
console.log('the third element of the array:', thirdElement);
const length = languages.length;
console.log('the length of the array:', length);
const lastElement = languages[languages.length - 1];
console.log('the last element:', lastElement);
